Layout/LineLength:
   Max: 130
Metrics/CyclomaticComplexity:
   Max: 8
Style/FrozenStringLiteralComment:
    Enabled: false
Style/StringLiterals:
    Enabled: false
Style/Documentation:
    Enabled: false
Metrics/AbcSize:
    Max: 25
Metrics/MethodLength:
    Max: 20
Metrics/ClassLength:
    Max: 150
AllCops:
  NewCops: enable
  Exclude:
    - 'bin/bundle'
    - 'db/schema.rb'
    - 'db/migrate/*'
    - 'db/seeds.rb'
